export { default as Home } from './home/Home';
export { default as About } from './about/About';
export { default as Work } from './work/Work';
export { default as Gallery } from './gallery/Gallery';
export { default as News } from './news/News';
export { default as Network } from './network/Network';
export { default as Donate } from './donate/Donate';
export {default as ContactUs} from './contactus/ContactUs';
export { default as OurStory } from './ourStory/OurStory';
export { default as Governers } from './governers/Governers';
export { default as Founder } from './founder/Founder';
export { default as Covid } from './covid/Covid';
export { default as Testimonial } from './testimonial/Testimonial';
export { default as NewsletterPage } from './newsletterPage/NewsletterPage';